
pipeline {
  agent any

  options { timestamps() }

  stages {
    stage('Check Java & Git') {
      steps {
        sh 'java -version || true'
        sh 'git --version'
      }
    }
  }

  post {
    success {
      archiveArtifacts artifacts: 'target/**/*.jar', fingerprint: true
      junit allowEmptyResults: true, testResults: 'target/surefire-reports/*.xml'
    }
    always {
      echo "Build finished: ${currentBuild.currentResult}"
    }
  }
}
