
pipeline {
  agent any

  options { timestamps() }

  stages {
    stage('Check Java & Git') {
      steps {
        sh 'java -version || true'
        sh 'git --version'
      }
    }

    stage('Build') {
      steps {
        // Using Maven Wrapper (mvnw). If you don't have it, see Option C below.
        sh './mvnw -B -DskipTests clean package'
      }
    }

    stage('Test') {
      steps {
        sh './mvnw test'
      }
    }

    stage('Package Info') {
      steps {
        sh 'ls -lah target || true'
      }
    }
  }

  post {
    success {
      archiveArtifacts artifacts: 'target/**/*.jar', fingerprint: true
      junit allowEmptyResults: true, testResults: 'target/surefire-reports/*.xml'
    }
    always {
      echo "Build finished: ${currentBuild.currentResult}"
    }
  }
}
